import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_applicationapp/generatedhamburgermenuwidget/generated/GeneratedEmergencyContactloginWidget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedhamburgermenuwidget/generated/GeneratedSingUpWidget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedhamburgermenuwidget/generated/GeneratedLoginWidget1.dart';

/* Frame Hamburger menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHamburgermenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 99.0,
        height: 173.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 156, 217, 243),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 23.0,
                child: GeneratedSingUpWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 26.0,
                child: GeneratedLoginWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedEmergencyContactloginWidget(),
              )
            ]),
      ),
    ));
  }
}
