import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedComponent13Widget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedRobo6Widget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedDEPtHLabWidget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/mobile_applicationapp/generatedwelcomepagewidget/generated/GeneratedCilhamburgermenuWidget.dart';

/* Frame Welcome page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 103.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 55.0,
                child: GeneratedDEPtHLabWidget(),
              ),
              Positioned(
                left: 351.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 35.0,
                child: GeneratedCilhamburgermenuWidget(),
              ),
              Positioned(
                left: 254.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 32.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 32.0,
                child: GeneratedComponent13Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 560.0,
                child: GeneratedRobo6Widget(),
              )
            ]),
      ),
    ));
  }
}
